### ISSUE TITLE
Typo in `/explore`

### ISSUE THREAD

**Issue by PhantomKnight287** [ujjwal-kr/night#9]
There is a typo in explore route at the end of the page.

Join my ~~discod~~ discord server

**Comment by ujjwal-kr** [comment]
thanks there are like a couple more typos I found, will fix it soon.

**Comment by PhantomKnight287** [comment]
#10 fixes it @ujjwal-kr

**Comment by ujjwal-kr** [comment]
oops I already fixed 2 of them in the latest commit
